# Image Manipulations and Image Spaces

In [1]:
import numpy as np
from PIL import Image

In [2]:
# Read an image
image = Image.open("4.1.06.tiff")

# Show the image
image.show()

In [3]:
# Transform the image to numpy array to manipulate it
image_array = np.array(image)

# Inspect the image array
print(f"Shape: {image_array.shape}")
print(f"Red channel:\n{image_array[:, :, 0]}")
print(f"Green channel:\n{image_array[:, :, 1]}")
print(f"Blue channel:\n{image_array[:, :, 2]}")

Shape: (256, 256, 3)
Red channel:
[[233 202 205 ... 233 235 239]
 [230 203 206 ... 232 234 235]
 [230 200 200 ... 232 233 235]
 ...
 [ 48  81  84 ...  75  68  84]
 [ 64 155 115 ...  81  83  85]
 [  0   0   0 ...   0   0   0]]
Green channel:
[[  0 217 218 ... 229 229 229]
 [217 217 217 ... 227 227 229]
 [217 217 216 ... 228 228 229]
 ...
 [ 43  58  43 ...  40  34  40]
 [ 58 155  99 ...  51  45  55]
 [  0   0   0 ...   0   0   0]]
Blue channel:
[[246 221 220 ... 227 227 226]
 [237 221 220 ... 227 225 228]
 [236 221 220 ... 227 227 226]
 ...
 [ 97  70  76 ...  72  72  81]
 [ 94 135  89 ...  84  74  80]
 [  0   0   0 ...   0   0   0]]


In [4]:
# Manipulation example: make the image darker
image_array_v1 = (image_array * 0.6).astype(np.uint8)
image_v1 = Image.fromarray(image_array_v1)
image_v1.show()

In [5]:
# Manipulation example: manipulate the red channel
image_array_v2 = image_array[:, :, 0]
image_v2 = Image.fromarray(image_array_v2)
image_v2.show()


In [6]:

# Why is it grey?
image_array_v2 = image_array.copy()
image_array_v2[:, :, 1] = 0  # Set green channel to 0
image_array_v2[:, :, 2] = 0  # Set blue channel to 0
image_v2 = Image.fromarray(image_array_v2)
image_v2.show()

In [10]:
# Transform RGB array to Lab array
from skimage.color import rgb2lab, lab2rgb

image_array_lab = rgb2lab(image_array)
# Inspect the image array
print(f"Shape: {image_array_lab.shape}")
print(f"L channel:\n{image_array_lab[:, :, 0]}")
print(f"a channel:\n{image_array_lab[:, :, 1]}")
print(f"b channel:\n{image_array_lab[:, :, 2]}")

# Transform Lab array to RGB array
image_array_rgb = lab2rgb(image_array_lab)

# Inspect the image array
print(f"Shape: {image_array_rgb.shape}")
print(f"Red channel:\n{image_array_rgb[:, :, 0]}")
print(f"Green channel:\n{image_array_rgb[:, :, 1]}")
print(f"Blue channel:\n{image_array_rgb[:, :, 2]}")

# Show the image
image = Image.fromarray((image_array_rgb * 255).astype(np.uint8))
image.show()

Shape: (256, 256, 3)
L channel:
[[56.06815251 85.70649804 86.15053474 ... 91.19291207 91.34603556
  91.63142667]
 [88.23904411 85.77686739 85.96353513 ... 90.61551135 90.71930243
  91.37102671]
 [88.21113414 85.56683406 85.28000986 ... 90.86603634 90.94247013
  91.3211776 ]
 ...
 [20.90022822 27.34665366 24.11179235 ... 21.87751504 19.39562593
  23.66076759]
 [26.51742594 63.4755503  43.19728362 ... 26.03168062 24.35542298
  27.4164282 ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]]
a channel:
[[93.62288486 -4.2523033  -3.9780591  ...  0.99443885  1.67341931
   2.86650061]
 [ 8.01890711 -3.92501161 -3.12997968 ...  1.68553016  2.01711271
   1.8468912 ]
 [ 7.83365831 -4.90474217 -4.5822508  ...  1.17023227  1.50912564
   1.50066387]
 ...
 [18.27126423 12.37713207 24.22905097 ... 21.93389944 23.14911905
  27.02166832]
 [11.83917891 -3.61124745  4.6495671  ... 19.85473825 22.23999884
  17.95949597]
 [ 0.          0.          0.         ...  0.          0.
   0.

In [11]:
# Transform RGB to HSV
from skimage.color import rgb2hsv, hsv2rgb

image_array_hsv = rgb2hsv(image_array)
# Inspect the image array
print(f"Shape: {image_array_hsv.shape}")
print(f"H channel:\n{image_array_hsv[:, :, 0]}")
print(f"S channel:\n{image_array_hsv[:, :, 1]}")
print(f"V channel:\n{image_array_hsv[:, :, 2]}")

# Histogram equalization on the V channel
from skimage.exposure import equalize_hist

image_array_hsv[:, :, 2] = equalize_hist(image_array_hsv[:, :, 2])
print(f"V channel after equalization:\n{image_array_hsv[:, :, 2]}")

# Transform HSV to RGB
image_array_rgb = hsv2rgb(image_array_hsv)

# Show the image
image = Image.fromarray((image_array_rgb * 255).astype(np.uint8))
image.show()

Shape: (256, 256, 3)
H channel:
[[0.82452575 0.53508772 0.52222222 ... 0.05555556 0.04166667 0.03846154]
 [0.775      0.53703704 0.53571429 ... 0.         0.03703704 0.02380952]
 [0.78070175 0.53174603 0.53333333 ... 0.03333333 0.02777778 0.05555556]
 ...
 [0.68209877 0.91304348 0.86585366 ... 0.84761905 0.81578947 0.84469697]
 [0.69444444 0.16666667 0.06410256 ... 0.81818182 0.87280702 0.86111111]
 [0.         0.         0.         ... 0.         0.         0.        ]]
S channel:
[[1.         0.08597285 0.06818182 ... 0.02575107 0.03404255 0.05439331]
 [0.08438819 0.08144796 0.06363636 ... 0.02155172 0.03846154 0.02978723]
 [0.08050847 0.09502262 0.09090909 ... 0.02155172 0.02575107 0.03829787]
 ...
 [0.55670103 0.28395062 0.48809524 ... 0.46666667 0.52777778 0.52380952]
 [0.38297872 0.12903226 0.22608696 ... 0.39285714 0.45783133 0.35294118]
 [0.         0.         0.         ... 0.         0.         0.        ]]
V channel:
[[0.96470588 0.86666667 0.8627451  ... 0.91372549 0.921568

# Compute Power

In [ ]:
def compute_power():
    raise NotImplementedError

# Compute Distortion

In [ ]:
def compute_distortion():
    raise NotImplementedError

# DVS

In [ ]:
def compute_pixel_current():
    raise NotImplementedError

In [ ]:
def compute_panel_power():
    raise NotImplementedError

In [12]:
from typing import Tuple

def displayed_image(
        i_cell: np.ndarray,
        vdd: float,
        p1: float = 4.251e-5,
        p2: float = -3.029e-4,
        p3: float = 3.024e-5,
        orig_vdd: float = 15,
        ) -> Tuple[np.ndarray, np.ndarray]:
    """
    Display an image on the OLED display taking into account the effect of DVS.

    :param i_cell: An array of the currents drawn by each pixel of the display.
    :param vdd: The new voltage of the display.
    """
    i_cell_max = (p1 * vdd * 1) + (p2 * 1) + p3
    image_rgb_max = (i_cell_max - p3) / (p1 * orig_vdd + p2) * 255
    out = np.round((i_cell - p3) / (p1 * orig_vdd + p2) * 255)
    original_image = out.copy()

    # Clip the values exceeding `i_cell_max` to `image_rgb_max`
    out[i_cell > i_cell_max] = image_rgb_max

    return original_image.astype(np.uint8), out.astype(np.uint8)

In [14]:
from scipy.io import loadmat

# Load the .mat file
mat_data = loadmat('sample_cell_current.mat')["I_cell_sample"]

# Inspect the loaded data
print(f"Shape: {mat_data.shape}")
print(f"Red channel:\n{mat_data[:, :, 0]}")
print(f"Green channel:\n{mat_data[:, :, 1]}")
print(f"Blue channel:\n{mat_data[:, :, 2]}")

image_array_orig, image_array_w_dvs = displayed_image(mat_data, 10)
image_orig = Image.fromarray(image_array_orig)
image_orig.show()
image_w_dvs = Image.fromarray(image_array_w_dvs)
image_w_dvs.show()


Shape: (176, 220, 3)
Red channel:
[[2.46842941e-04 2.24526275e-04 2.03522353e-04 ... 9.45645098e-05
  9.45645098e-05 9.45645098e-05]
 [2.46842941e-04 2.24526275e-04 2.03522353e-04 ... 9.45645098e-05
  9.45645098e-05 9.45645098e-05]
 [2.46842941e-04 2.24526275e-04 2.03522353e-04 ... 9.45645098e-05
  9.45645098e-05 9.45645098e-05]
 ...
 [2.88850784e-04 2.78348824e-04 2.67846863e-04 ... 3.32171373e-04
  3.21669412e-04 3.21669412e-04]
 [2.88850784e-04 2.78348824e-04 2.67846863e-04 ... 3.32171373e-04
  3.32171373e-04 3.21669412e-04]
 [2.88850784e-04 2.78348824e-04 2.67846863e-04 ... 3.32171373e-04
  3.32171373e-04 3.11167451e-04]]
Green channel:
[[1.41823333e-04 1.20819412e-04 1.10317451e-04 ... 7.22478431e-05
  6.69968627e-05 6.69968627e-05]
 [1.36572353e-04 1.26070392e-04 1.10317451e-04 ... 7.22478431e-05
  6.69968627e-05 6.69968627e-05]
 [1.31321373e-04 1.20819412e-04 1.10317451e-04 ... 7.22478431e-05
  6.69968627e-05 6.69968627e-05]
 ...
 [1.73329216e-04 1.62827255e-04 1.57576275e-04 ..